---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u7175693/public_html/rendi.sttsappi.ac.id
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
